### ISSUE TITLE
reduce LaTeX installation

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/homepage-toolbox#103]
use options to reduce the size

**Comment by chrbeckm** [comment]
```
O

D
S

R

C
ijklmnosvSwxyzABCI
```

**Comment by LuckyJosh** [comment]
The consensus from the last meeting was, to stay with the full TexLive install as the
default, but add a section to the instructions on how to reduce the size if the full
install is causing some issues ... (like slow wifi or small flash drives on tablets for example).
