### ISSUE TITLE
Alternative Plugin(s) to LaTeX-Workshop/LaTeX language support

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/homepage-toolbox#122]
I found these two Plugins:
[TexLab LSP-Client](https://marketplace.visualstudio.com/items?itemName=efoerster.texlab)
[latex-syntax](https://marketplace.visualstudio.com/items?itemName=vomout.latex-syntax)

The first one is a client to the [TexLab LSP-Server](https://texlab.netlify.app/).
On a first glance, the completion seems to work quite well. 
The second one seems to be designed to work well with the first one, but is not necessary.

**Comment by maxnoe** [comment]
LaTeX-Language support is now available in the codium extension store, so we can keep using it.

**Comment by maxnoe** [comment]
@LuckyJosh I am a fan of LSP, but does it require the TexLab LS installed separately? Or does it work with just installing the plugin?

**Comment by LuckyJosh** [comment]
@maxnoe I'm not absolutly sure, but I'd guess that the lsp gets installed automatically, when you install the plugin.

**Comment by LuckyJosh** [comment]
> 
> @LuckyJosh I am a fan of LSP, but does it require the TexLab LS installed separately? Or does it work with just installing the plugin?

I tested it just now, if the TexLab-LS is not installed you get a notification with the option to install it.
