### ISSUE TITLE
El Capitan Locale fix

### ISSUE THREAD

**Issue by mennthor** [pep-dortmund/homepage-toolbox#16]
Install manual for OSX:
When using El Capitan the Locale is not set correctly.
This will cause python to raise "unknown locale errors".
Add:

```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

to `~/.profile` to resolve.
`en_US` must be set to the correct system encoding , eg. `de_DE` for german.

**UPDATE 30.09.16**
I googled a bit more and this is _always_ given as the solution.
Not sure, how this is handled in e.g. Ubuntu

**Comment by MaxNoe** [comment]
I think this is not needed anymore. Did not occure the last few years.
