### ISSUE TITLE
Showing missing XServer in the Terminal

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/homepage-toolbox#173]
Just recently I added the following condition to my `wsl` `.bashrc`:

```bash
if ! xhost >& /dev/null ; then 
echo -e "\033[31;1mDisplay ($DISPLAY) not found\033[0m: You might want to turn on the XServer" ; 
fi
```
If the XServer is not running it will show as the first line in every new terminal:

![grafik](https://user-images.githubusercontent.com/5610010/144915732-f2d23dc4-fd18-4582-af6f-bda2d3153182.png)

The red/bold formatting is just my personal preference.

Should we add this to the Win10-instructions?

**Comment by jpherdi** [comment]
I like it.

**Comment by chrbeckm** [comment]
Additionally we could add instructions to place the XServer in the AutoStart list.

**Comment by jpherdi** [comment]
Even better 👍
