### ISSUE TITLE
latex language support discontinued

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/homepage-toolbox#176]
> From VSCode 1.64, the VS Code team has decided to provide built-in support for the LaTeX grammar. So this extension only supports VSCode <1.64.

- [ ] Check if the support is transferred to VS Codium
- [ ] If not, find alternatives

https://marketplace.visualstudio.com/items?itemName=torn4dom4n.latex-support

**Comment by jpherdi** [comment]
Latex-workshop is anyway the best extension for vscode+latex in my opinion.

**Comment by LuckyJosh** [comment]
I'd say that [LaTeX-Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) is better suited for advanced users. My suggestion would be the [TeXLab LSP-Client](https://marketplace.visualstudio.com/items?itemName=efoerster.texlab).

Any opinions?

**Comment by maxnoe** [comment]
Our main reason for installing the plugin was the syntax highlighting, if that comes out of the box now, we don't really need to have everyone install any extension during the setup process.

We also don't let people install the python extension, right?

So maybe just dropping it would be fine.

> My suggestion would be the [TeXLab LSP-Client](https://marketplace.visualstudio.com/items?itemName=efoerster.texlab).

I use the TeXLab LSP in neovim and I am pretty happy with it. So we might recommend it.

**Comment by LuckyJosh** [comment]
>  We also don't let people install the python extension, right?

That is true, the only plugin in the instructions was the LaTeX one.
I remember many participants ended up installing it
during the workshop, because VS Code recommends
it (when opening a python file).

But I agree, that the plugins dont have to be part of the install instructions.

**Comment by chrbeckm** [comment]
But then it should be best to explain this specific part when presenting the first exercise for python or LaTeX. Maybe they already installed it, or we can show them what the benefits are.

**Comment by jpherdi** [comment]
This can be closed, right?
