### ISSUE TITLE
Latex Installation Script

### ISSUE THREAD

**Issue by jpherdi** [pep-dortmund/homepage-toolbox#184]
Could you please explain, why you decided to have the people to download and run a "shady" bash script in the latex installation instead of the previous installation, where they perform every step for their own?

I don't like this and would like a discussion about this.

**Comment by LuckyJosh** [comment]
Interesting timing, I just noticed this yesterday and was kind of surprised too. If I recall correctly our solution for the texlive installation was along the lines of
"let the full install be the default, and have a script
for the tiny installation for low memory devices" 🤔

**Comment by maxnoe** [comment]
I concur. Last time we discussed this in a meeting, we decided against having a script. Why was this merged?

**Comment by SepplL** [comment]
In this case, i forgot about this meeting.
The main reason for merging the changes was the amount of time and development needed for the new script. It went through multiple stages and I got the feeling that the necessity was not in doubt at any stages in the project.
Furthermore, I don't think that copy-pasting a few commands is really that much of an educational benefit. The few people that really deep-dive into the commands are more than capable of looking at a bash script.
I agree that downloading and running a bash script is not the best way, but again, the changes were discussed and made in the branch and the actual idea was not discussed in this way.

Perhaps a good middle ground is to leave the full installation the way it was before and only use the install-script for the version with little disk space available.
This way, the copy-paste experience is preserved, but we don't have to pipe a txt file into the installation command for using just a few packages.

Anyway, it is quite possible to undo the changes. But next time, before we improve an install script to the point where it can be merged, we should have this ground discussion as a first step.

**Comment by jpherdi** [comment]
Yes, I would like it, when it would be undone.

I fully get your point, that it is weird, that this was pursued for so long and now everyone does not approve.. :D Maybe these people could say something to this again.
