### ISSUE TITLE
Windows 10 and 11 Installation Instructions: VS Code section

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/homepage-toolbox#232]
Could anyone remind what our latest/current stance for the following 'issues' is:
If we dont have an official stance, I'd take your opinions as well 😄 

#### VS Code vs. VS Codium
I'd think it is kind of moot installing VS Codium on a Windows System. 
I'm not against of informing about the differences, but I'd say the issue
wouldn't even register with users new to the content of the workshop.

#### VS Code Server and the WSL
Since the python installation is in the wsl, the plugins for VS Code cannot detect the installed packages,
when VS Code is installed on the Windows side. Which leaves two (and a half) options:

1. Installing VS Code on the wsl side (or on both)
2. Using the WSL Server extension (which is not available for VS Codium)

I'd argue for the 2. option, as it seems to be the least complex option. 

#### Plugin for LaTeX
As mentioned in #176 VS Code has LaTeX syntax highlighting build in (since version 1.64).
Two Plugins for code completion are:

1. [LaTeX-Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop)
2. [TeXLab LSP-Client](https://marketplace.visualstudio.com/items?itemName=efoerster.texlab)

Again I'd argue for option 2., since it is less complex of a plugin.

**Comment by chrbeckm** [comment]
If I remember correctly from the last discussion about this, we argued for VSCode on Windows and the WSL Extension. The arguments for VSCodium don't really apply on Windows, as you are actively using a Microsoft product.

Regarding the plugin, I can't provide feedback from experience. For `LaTeX-Workshop` Ludwig wrote a blog post, how to set it up in unison to the workflow we present. If `TeXLab LSP-Client` doesn't need that, it would be favorable in my view. We could add a section about `LaTeX-Workshop` and how to set it up, maybe somewhere else. For people interested in testing that one.

**Comment by jpherdi** [comment]
I think this was also fixed. I will close it for now.
