### ISSUE TITLE
Floating Help Button for Installation Instructions?

### ISSUE THREAD

**Issue by aknierim** [pep-dortmund/homepage-toolbox#238]
I think we could add a floating help button to the installation instruction pages that would ref `problem.html`, i.e. the "Hilfe" page. The button could look something like in the screenshot below and would stay in the lower right corner. Even though we already have the help page in the header navbar, I think this still may be a good addition.

![image](https://github.com/pep-dortmund/homepage-toolbox/assets/32365583/4834e6a6-9d08-413d-ac57-c24ef2358dc5)

**Comment by aknierim** [comment]
Alright, will open a PR then 👍

**Comment by chrbeckm** [comment]
On that note, do we have analytics to our website? And could we see how many people lick this button? @maxnoe
