### ISSUE TITLE
Missing Glyph

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/homepage-toolbox#244]
Might be an Issue with my mobile browser,
but the "back to top"-button looks like this:

![image](https://github.com/pep-dortmund/homepage-toolbox/assets/5610010/52b4f1a3-8add-4f9e-9b6a-aff28705c994)

**Comment by jpherdi** [comment]
Same for me

**Comment by aknierim** [comment]
Oh damn, I tested it with  the simulated mobile view in Firefox, but forgot to check with my mobile. Will fix it later today.
