### ISSUE TITLE
Mini-LaTeX installation package list not consistent

### ISSUE THREAD

**Issue by SepplL** [pep-dortmund/homepage-toolbox#252]
The package list from the Mini installation is not consistent with the package list installed by the GitHub CLI bot.
Do we want that inconsistency or is that based on changes in the past?

I thought the Mini-LaTeX installation should provide all necessary packages to work in the toolbox environments without having to install additional packages.
I know this is a rather small issue, but I think the inconsistency in the package list is not necessary.

**Comment by maxnoe** [comment]
No, the mini installation is meant to provide what people need for the latex template, i.e. it's probably not including `beamer` to build the slides here.

**Comment by maxnoe** [comment]
> not tabularray for example

Ah, then it's probably just outdated indeed, tabularray is a recent addition
