### ISSUE TITLE
Mini-LaTeX 

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/homepage-toolbox#254]
Do we want to maintain two lists of packages for minimal installations of LaTeX?
We could change the mini-latex-instruction, so we use the list from the toolbox-workshop repo. This includes some packages not strictly necessary for the AP, but makes it easier to exchange the packages we show.

**Comment by aknierim** [comment]
I'd be in favor of using the toolbox-workshop repo list. Makes it easier to keep up with changes to the repos...
