### ISSUE TITLE
Add fc-cache to `LaTeX` installation

### ISSUE THREAD

**Issue by SepplL** [pep-dortmund/homepage-toolbox#267]
To reduce time for first exercise

**Comment by maxnoe** [comment]
How does `fc-cache` help for the LaTeX exercises?

**Comment by LuckyJosh** [comment]
Yeah sorry brain lag ... i meant the font caching from latex itself,
by compiling some document.

**Comment by maxnoe** [comment]
Ah, that would be:

```
luaotfload-tool --update --force
```
