### ISSUE TITLE
Changes for 2024

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/homepage-toolbox#277]
~Tabs in Navbar aufräumen zu:~
- ~Installation~
- ~Material~
- ~Hilfe~
- ~Mehr~
    - ~Über~
    - ~Blog~
    - ~Links~
    - ~(Archiv) oder nur über das Material verlinken~
- ~FAQ rausnehmen~

Archiv verkleinern
- 2023 als einziges Material behalten
- vor dem Workshop 2024 ins Archiv verschieben
- dann notes.md mit 2024er Material befüllen
- wenn vollständig 2023er Material entfernen
- static links für Lesezeichen

- ~TOC in den Installationsanleitungen, vor allem Windows~
- verlinkten Inhalt in links.md überprüfen
- Einige haben sich für das Praktikum wohl einen Laptop gekauft und hätten sich gewünscht, dass irgendwo geschrieben stände, dass man über eine englische Tastatur und Linux OS nachdenken könnte. Eventuell können wir hier auf der Installationsübersichtsseite einen kurzen Abschnitt zu machen.

Plan für 2024 anpassen, auch in der Anmeldung.

**Comment by aknierim** [comment]
Habe bereits die Navbar angepasst, PR folgt

**Comment by aknierim** [comment]
>     * TOC in den Installationsanleitungen, vor allem Windows

Merged in #281

**Comment by aknierim** [comment]
> Einige haben sich für das Praktikum wohl einen Laptop gekauft und hätten sich gewünscht, dass irgendwo 
> geschrieben stände, dass man über eine englische Tastatur und Linux OS nachdenken könnte. Eventuell können wir
> hier auf der Installationsübersichtsseite einen kurzen Abschnitt zu machen.

Hier könnten wir vielleicht auch noch in dem kurzen Abschnitt einen Artikel/Blog-Post wie [diesen](https://endler.dev/2018/keyboard/)  als Motivation für das US-Layout verlinken.
