### ISSUE TITLE
Links to old versions of the workshop materials are not working

### ISSUE THREAD

**Issue by VukanJ** [pep-dortmund/homepage-toolbox#287]
To reproduce, go to the Archive and try accessing the 2019 material

**Comment by aknierim** [comment]
That may be due to a restructure of the repo. But we talked about getting rid of older archived material anyway. The plan would be to only include the current and previous year.

**Comment by VukanJ** [comment]
Personally I don't see the harm in providing the old material, usually one has good reason to search for it. But either way is fine I guess, as we have the repo

**Comment by aknierim** [comment]
I think the idea was to have an archive that is less cluttered... I see your point though. But the plan was to still keep the archive inside the repo, iirc.

The commit that broke the links is https://github.com/pep-dortmund/homepage-toolbox/commit/c55ed6979a649606eca7ad2c2cf07e5a1d9de964; notice the double slashs in front of links for material up to 2021.

**Comment by maxnoe** [comment]
> Personally I don't see the harm in providing the old material, usually one has good reason to search for 

What would be a good reason to search for lectures that are for software that is outdated by 5 years?

**Comment by VukanJ** [comment]
I wanted to look up something booktabs related, which has been replaced.

**Comment by maxnoe** [comment]
Booktabs docs can be found here: https://ctan.org/pkg/booktabs/ or using `texdoc booktabs`

**Comment by aknierim** [comment]
You can look at the 2022 material. We switched to `tabularray` in 2023.

**Comment by VukanJ** [comment]
Very nice, thanks for letting me know that there is a manual @maxnoe Instead of showing slides we should consider give students a list of texdoc commands.

**Comment by maxnoe** [comment]
We should  teach people to find things in documentation, yes, instead of using 5 year old material for things they want to do now, yes.

Another general solution for accessing old information on websites is the internet archive:
http://web.archive.org/web/20200921003609/https://toolbox.pep-dortmund.org/files/archive/2019/latex.pdf

**Comment by VukanJ** [comment]
Well, thanks for the lesson.
