### ISSUE TITLE
Fedora additional packages

### ISSUE THREAD

**Issue by SepplL** [pep-dortmund/homepage-toolbox#294]
Maybe we can mention this in some appendix or further information section?

Needed to install multiple `Perl` packages to get `latexmk` running on fedora:

- `perl-File-Copy`
- `perl-Time-HiRes`
- `perl-Unicode-Normalize`
- `perl-sigtrap`
- `perl-meta-notation`

can this happen on other systems as well? Or is it a local and unique `Perl`-install weirdness on my machine?

Open for discussion and suggestions.

**Comment by aknierim** [comment]
Not a local weirdness on your machine. We encountered the same problem a few weeks ago on a machine with Fedora, too.  So we should definitely mention this somewhere.

```
$ dnf repoquery --requires latexmk
```
should list all dependencies for `latexmk`. IIRC, we fixed it by installing `latexmk` separately from TeXLive via `dnf`.

**Comment by SepplL** [comment]
```
$ dnf repoquery --requires latexmk
```
returns the list
```
ghostscript
perl(Config)
perl(Cwd)
perl(Digest::MD5)
perl(Encode)
perl(File::Basename)
perl(File::Copy)
perl(File::Find)
perl(File::Glob)
perl(File::Path) >= 2.08
perl(File::Spec::Functions)
perl(FileHandle)
perl(List::Util)
perl(Time::HiRes)
perl(Unicode::Normalize)
perl(feature)
perl(sigtrap)
perl(strict)
perl(utf8)
perl(warnings)
tex-latex-bin
xdg-utils
```

In order to keep all installs fairly similar and consistent I would lean towards just mentioning the command or package list.
I don't think there are too many Fedora users out there using this install protocol that are lost with a `Perl` error message the first time they use `latexmk`.
But a simple hint would not be too much work.

**Comment by maxnoe** [comment]
Ubuntu is loosing a bit of user base over e.g. the snap curfuffle...

A one-liner  (tested in latest fedora docker) would be:
```
 dnf install -y $(dnf repoquery --requires --resolve latexmk | grep perl)
```
I think we should add that to the install instructions.

**Comment by aknierim** [comment]
That is a neat solution
