### ISSUE TITLE
Python 2.7 pip install fails with "Illegal byte sequence"

### ISSUE THREAD

**Issue by zevix** [pep-dortmund/homepage-toolbox#41]
ConEmu build: 180626 x64
OS version: Windows 10 x64
Used shell version: CMD

Python 2.7's pip fails when CMD runs under ConEmu:

C:\Users\zeev.kotzer>pip install Kivy --upgrade                                                    
Collecting Kivy                                                                                    
  Downloading https://files.pythonhosted.org/packages/f7/98/d74b2c19eb28dcf36450c979c19676741891ca8
a54af0a7069e445552663/Kivy-1.10.1-cp27-cp27m-win_amd64.whl (4.3MB)                                 
    1% |Could not install packages due to an EnvironmentError: **[Errno 42] Illegal byte sequence**    
                                                                                                                                                                                               
This can be worked around by adding "--progress-bar off", but inconvenient, and problematic for novice users ...

**Comment by MaxNoe** [comment]
I dont understand your issue. This is  a jekyll webpage for a workshop that is strictly python 3 since the first workshop in 2012.

Can you elaborate why you open2d this issue?

**Comment by zevix** [comment]
Oops, sorry, I submitted this in the wrong browser tab..
