### ISSUE TITLE
Windows Subsystem

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/homepage-toolbox#57]
There were changes after the Workshop 2018 in the windows subsystem.
I tried the installation guide recently and everything worked.

If something misbehaves check the two links below, send to me by Lars from E2
https://www.omgubuntu.co.uk/2019/07/ubuntu-wsl-metapackage-install
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack

**Comment by MaxNoe** [comment]
> There were changes after the Workshop 2018 in the windows subsystem.
I tried the installation guide recently and everything worked.

If everything worked, what's the issue here?

**Comment by chrbeckm** [comment]
had a chat with @LuckyJosh yesterday,
intention of a good to know thing
