### ISSUE TITLE
Installation of dependecy on Ubuntu 18.04

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/homepage-toolbox#59]
Trying to install the dependencies you get the following error for the package `nodejs-legacy`:
```
❯ sudo apt install nodejs-legacy                                         (base) 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package nodejs-legacy is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  nodejs:i386 nodejs

E: Package 'nodejs-legacy' has no installation candidate
```
Installing the given replacement packages `nodejs:i386 nodejs` seems to work.
Yet I'm not sure for what purpose this dependency is needed and what to look for. :thinking:

**Comment by chrbeckm** [comment]
I installed the packages
`sudo apt install ruby-dev nodejs libxml2-dev libxslt1-dev `
and it works. Maybe that helps.

**Comment by MaxNoe** [comment]
> nodejs:i386

You only need one! The i386 is the 32 bit build.
nodejs is used for serving the site locally I think (It's a dependency of jekyll)

**Comment by MaxNoe** [comment]
fixed
