### ISSUE TITLE
Known VSCode Bug on MacOS (workaround)

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/homepage-toolbox#70]
The integrated terminal of vscode does *something* to the PATH variable, with the effect of placing anaconda at the end of the path. Therefore the python version used by the terminal wont be the anaconda one.

There is a workaround, taken from this [github issue](https://github.com/microsoft/vscode/issues/70248#issuecomment-472258747):
This entry has to be added to the  `settings.json` file:

```
"terminal.integrated.env.osx": {
		"PATH": ""
}
```

**Comment by jpherdi** [comment]
This is outdated, right?
