### ISSUE TITLE
sitepage for problem-solving

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/homepage-toolbox#90]
Since we got very unspecified questions about problems with the installation,
i suggest we could write a page about how to ask when there are problems.

On this page we could collect fixes to known bugs and a little instruction on E-Mail Requests.
A bulletpoint list may be the best idea, like
- write to this e mail address
- name your OS
- which programm causes the problem
- add the error code or a screenshot

**Comment by MaxNoe** [comment]
Very good idea!

**Comment by chrbeckm** [comment]
I will see what i can produce
