### ISSUE TITLE
sourcing anaconda in bashrc still recommended?

### ISSUE THREAD

**Issue by VukanJ** [pep-dortmund/homepage-toolbox#92]
On the installation page we are recommending to source anaconda in the bashrc. Do we really want to recommend that? This can be potentially problematic since the python version of cmake does not always function like normal cmake which can lead to major headaches when one tries to compile a cmake based project. At least when you don't know what anaconda is doing behind your back. And there is no real way (i think) to get rid of this cmake version (by redirecting to another cmake executable) while staying in the anaconda environment, without "breaking" some python packages.
Example:
```
➜  ~ which cmake   
/usr/bin/cmake
➜  ~ conda activate 
(base) ➜  ~ which cmake
/home/vukan/.local/anaconda3/bin/cmake
```

**Comment by LuckyJosh** [comment]
It is worth to be mentioned somewhere, maybe on the new "Hilfe" page.

However I think the target audience wont use cmake anytime soon and typing `conda activate` every time they want to use python is another step to be remembered
(and there are already to many)

One way to get around this problem when anaconda is activated is, to use the whole path to the executable to call the right `cmake` without going through the `PATH`.
`/usr/bin/cmake ...`

**Comment by VukanJ** [comment]
Sure that would work when you finally realize what the problem actually is. Still inconvenient, no? And quite often cmake is called from third party installation scripts that you don't want to edit every time. Maybe they won't use cmake themselves but software they need needs to be be compiled with cmake

**Comment by MaxNoe** [comment]
Yes, but that depends on many things. E.g. I want to use the cmake from conda when istalling a python module with c/c++ extensions into the conda environment.

This is so far over the heads of anyone attending this workshop, that mentioning it will create more confusion that good imho.

**Comment by MaxNoe** [comment]
An what do you mean by the python version of cmake? There is no python version of cmake and anacoda comes with standard, up do date version of cmake

**Comment by MaxNoe** [comment]
Also: "source CONDA_PATH/etc/profile.d/conda.sh" is not optional, this is always needed.

The question is if putting `conda activate` into the bashrc is a good thing.
And I would argue for the workshop, yes. Later, when more complex software is needed and/or multiple conda / python environments, probably better idea to not put it in and be explicit anytime you need to use it

**Comment by VukanJ** [comment]
Ok, i see. I would just add that the installation instructions are not only used by beginners attending the workshop, but I see your point, maybe we could add a comment like "This is useful for the workshop: Add this to the bashrc [...]".
-- An what do you mean by the python version of cmake?
The version used by anaconda can be a different one from the one that is normally installed on the system which can cause problems. At least in my experience. I think I tried to install to install a package and did not notice for a while that the installation failed again and again because of this

**Comment by MaxNoe** [comment]
More probably the reason was not the different cmake version, but the libraries included with anaconda that are linked against, when the conda environment is activated.

Building projects with anaconda is quite a bit tricky, and the most reliable way is to just use libraries installed into the conda environment and not link against a mix of system and conda libraries.

**Comment by MaxNoe** [comment]
See for example:
https://github.com/conda-forge/root-feedstock
