### ISSUE TITLE
Installation in 2020 & Biber issue

### ISSUE THREAD

**Issue by SepplL** [pep-dortmund/homepage-toolbox#93]
Since 2020 is happening when installing tex the Path includes a texlive/2020/bin and the filename in Anaconda changes from Anaconda3-2019.07-Linux to Anaconda3-2020.02-Linux.
Also the tex settings require an init-usertree command in the beginning.
Furthermore the Biber installation does not seem to work. After reinstalling everything and changing path as mentioned Biber does not start.
Thanks for help!

**Comment by MaxNoe** [comment]
Hi,

I just downloaded and installed TeXLive 2020 on Linux and cannot reproduce your issue.
Everything seems like it is described on the homepage.

There is only one `bin/x86_64-linux` directory and that contains the biber exe:
```
$ which biber
/home/maxnoe/.local/texlive/2020/bin/x86_64-linux/biber
```

The tlmgr option commands also ran without issue for me.

What exactly were you doing and on which distribution / OS?

**Comment by SepplL** [comment]
After reinstalling TeX the Issue is fixed. I got no idea what went wrong the first time.
Thanks for your help!
