### ISSUE TITLE
Windows10 and OneDrive

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/homepage-toolbox#95]
This issue is meant to be a heads up, more than anything.
This is not a complicated fix, I am going to take a look at it today or tomorrow.

Triggert by the email to the emaillist today I discovered the following:

Windows seems to put the Desktop-Folder into a OneDrive-Folder.
I am not sure if this is opt-in or opt-out but I assume the latter.

This is a problem for the Windows10 instructions since you have to navigate to
the Desktop at some point.

**Comment by MaxNoe** [comment]
Just use downloads instead of Desktop?

**Comment by LuckyJosh** [comment]
@MaxNoe yes, that would be the easiest. 👍

**Comment by jpherdi** [comment]
Was this fixed in the manuals?

**Comment by chrbeckm** [comment]
Do we still need this reminder with the new WSL2 instructions? We don't save anything to the desktop now.

**Comment by LuckyJosh** [comment]
I'd say this is obsolete 👍
